export const REGISTER_SUCCESS="REGISTER_SUCCESS"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"
export const REGISTER_FAIL="REGISTER_FAIL"
export const LOAD_USER="LOAD_USER"
export const LOAD_USER_SUCCESS="LOAD_USER_SUCCESS"
export const AUTH_ERROR="AUTH_ERROR"
export const LOAD_FAIL="LOAD_FAIL"


// export const LOGIN_STYLIST_START = "LOGIN_STYLIST_START";
// export const LOGIN_STYLIST_SUCCESS = "LOGIN_STYLIST_SUCCESS";
// export const LOGIN_STYLIST_FAILURE = "LOGIN_STYLIST_FAILURE";

// export const FETCH_STYLISTS_START = "FETCH_STYLISTS_START";
// export const FETCH_STYLISTS_SUCCESS = "FETCH_STYLISTS_SUCCESS";
// export const FETCH_STYLISTS_FAILURE = "FETCH_STYLISTS_FAILURE";

// export const ADD_STYLIST_START = "ADD_STYLIST_START";
// export const ADD_STYLIST_SUCCESS = "ADD_STYLIST_SUCCESS";
// export const ADD_STYLIST_FAILURE = "ADD_STYLIST_FAILURE";

// export const DELETE_STYLIST = "DELETE_STYLIST";

// export const STYLIST_UPDATE_START = "STYLIST_UPDATE_START";
// export const STYLIST_UPDATE_SUCCESS = "STYLIST_UPDATE_SUCCESS";
// export const STYLIST_UPDATE_FAILURE = "STYLIST_UPDATE_FAILURE";

// export const TOGGLE_STYLIST = "TOGGLE_STYLIST";

// export const AUTH_ERROR="AUTH_ERROR"
// export const REGISTER_FAILURE="REGISTER_FAILURE"